import React from 'react';
import '../App.css';

function PrivacyPolicy() {
    return (
        <div className="main-content-area">
            <div className="page-card">
                <h1>Privacy Policy for Gulf Career Gateway</h1>
                <p><em>Last updated: October 27, 2025</em></p>
                <p>Gulf Career Gateway ("us", "we", or "our") operates the Gulf Career Gateway website (the "Service"). This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.</p>

                <hr />

                <h2>Definitions</h2>
                <ul>
                    <li><strong>Service:</strong> The Gulf Career Gateway website.</li>
                    <li><strong>Personal Data:</strong> Data about a living individual who can be identified from those data.</li>
                    <li><strong>Usage Data:</strong> Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                    <li><strong>User:</strong> The individual using our Service.</li>
                </ul>

                <hr />

                <h2>Information Collection and Use</h2>
                <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
                <h3>Types of Data Collected</h3>
                <h4>Personal Data</h4>
                <p>While using our Service, especially when applying for a vacancy, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:</p>
                <ul>
                    <li>Email address</li>
                    <li>First name and last name</li>
                    <li>Phone number</li>
                    <li>Resume / Curriculum Vitae (CV)</li>
                </ul>
                <h4>Usage Data</h4>
                <p>We may also collect information on how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol (IP) address, browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, and other diagnostic data.</p>

                <hr />

                <h2>Use of Data</h2>
                <p>Gulf Career Gateway uses the collected data for various purposes:</p>
                <ul>
                    <li>To provide and maintain our Service</li>
                    <li>To notify you about changes to our Service</li>
                    <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
                    <li>To provide customer support</li>
                    <li>To gather analysis or valuable information so that we can improve our Service</li>
                    <li>To monitor the usage of our Service</li>
                    <li>To detect, prevent and address technical issues</li>
                    <li>To forward your application to potential employers with your consent</li>
                </ul>

                <hr />

                <h2>Retention of Data</h2>
                <p>Gulf Career Gateway will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>

                <hr />

                <h2>Security of Data</h2>
                <p>The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>

                <hr />

                <h2>Links to Other Sites</h2>
                <p>Our Service may contain links to other sites that are not operated by us. If you click a third-party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.</p>

                <hr />

                <h2>Changes to This Privacy Policy</h2>
                <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. We will let you know via a prominent notice on our Service, prior to the change becoming effective and update the "last updated" date at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes.</p>

                <hr />

                <h2>Contact Us</h2>
                <p>If you have any questions about this Privacy Policy, please contact us by visiting the contact page on our website.</p>
            </div>
        </div>
    );
}

export default PrivacyPolicy;